// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	domain "github.com/dhuki/go-ledger-system/internal/infra/database/repository/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransaction is an autogenerated mock type for the Transaction type
type MockTransaction struct {
	mock.Mock
}

type MockTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransaction) EXPECT() *MockTransaction_Expecter {
	return &MockTransaction_Expecter{mock: &_m.Mock}
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockTransaction) Transaction(ctx context.Context, fn func(domain.DomainRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(domain.DomainRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockTransaction_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(domain.DomainRepository) error
func (_e *MockTransaction_Expecter) Transaction(ctx interface{}, fn interface{}) *MockTransaction_Transaction_Call {
	return &MockTransaction_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockTransaction_Transaction_Call) Run(run func(ctx context.Context, fn func(domain.DomainRepository) error)) *MockTransaction_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(domain.DomainRepository) error))
	})
	return _c
}

func (_c *MockTransaction_Transaction_Call) Return(_a0 error) *MockTransaction_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Transaction_Call) RunAndReturn(run func(context.Context, func(domain.DomainRepository) error) error) *MockTransaction_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransaction creates a new instance of MockTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransaction {
	mock := &MockTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
