// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	dao "github.com/dhuki/go-ledger-system/internal/infra/database/dao"

	mock "github.com/stretchr/testify/mock"
)

// MockTrxLedgerEntry is an autogenerated mock type for the TrxLedgerEntry type
type MockTrxLedgerEntry struct {
	mock.Mock
}

type MockTrxLedgerEntry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrxLedgerEntry) EXPECT() *MockTrxLedgerEntry_Expecter {
	return &MockTrxLedgerEntry_Expecter{mock: &_m.Mock}
}

// InsertLedgerEntriesBulk provides a mock function with given fields: ctx, entries
func (_m *MockTrxLedgerEntry) InsertLedgerEntriesBulk(ctx context.Context, entries []dao.LedgerEntries) error {
	ret := _m.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for InsertLedgerEntriesBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dao.LedgerEntries) error); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLedgerEntriesBulk'
type MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call struct {
	*mock.Call
}

// InsertLedgerEntriesBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []dao.LedgerEntries
func (_e *MockTrxLedgerEntry_Expecter) InsertLedgerEntriesBulk(ctx interface{}, entries interface{}) *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call {
	return &MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call{Call: _e.mock.On("InsertLedgerEntriesBulk", ctx, entries)}
}

func (_c *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call) Run(run func(ctx context.Context, entries []dao.LedgerEntries)) *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dao.LedgerEntries))
	})
	return _c
}

func (_c *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call) Return(_a0 error) *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call) RunAndReturn(run func(context.Context, []dao.LedgerEntries) error) *MockTrxLedgerEntry_InsertLedgerEntriesBulk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrxLedgerEntry creates a new instance of MockTrxLedgerEntry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrxLedgerEntry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrxLedgerEntry {
	mock := &MockTrxLedgerEntry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
