// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	dao "github.com/dhuki/go-ledger-system/internal/infra/database/dao"

	mock "github.com/stretchr/testify/mock"
)

// MockTrxAccountBalance is an autogenerated mock type for the TrxAccountBalance type
type MockTrxAccountBalance struct {
	mock.Mock
}

type MockTrxAccountBalance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrxAccountBalance) EXPECT() *MockTrxAccountBalance_Expecter {
	return &MockTrxAccountBalance_Expecter{mock: &_m.Mock}
}

// GetAccountsForUpdate provides a mock function with given fields: ctx, accountNumbers
func (_m *MockTrxAccountBalance) GetAccountsForUpdate(ctx context.Context, accountNumbers []string) ([]*dao.AccountBalances, error) {
	ret := _m.Called(ctx, accountNumbers)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsForUpdate")
	}

	var r0 []*dao.AccountBalances
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*dao.AccountBalances, error)); ok {
		return rf(ctx, accountNumbers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*dao.AccountBalances); ok {
		r0 = rf(ctx, accountNumbers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.AccountBalances)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, accountNumbers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrxAccountBalance_GetAccountsForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsForUpdate'
type MockTrxAccountBalance_GetAccountsForUpdate_Call struct {
	*mock.Call
}

// GetAccountsForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumbers []string
func (_e *MockTrxAccountBalance_Expecter) GetAccountsForUpdate(ctx interface{}, accountNumbers interface{}) *MockTrxAccountBalance_GetAccountsForUpdate_Call {
	return &MockTrxAccountBalance_GetAccountsForUpdate_Call{Call: _e.mock.On("GetAccountsForUpdate", ctx, accountNumbers)}
}

func (_c *MockTrxAccountBalance_GetAccountsForUpdate_Call) Run(run func(ctx context.Context, accountNumbers []string)) *MockTrxAccountBalance_GetAccountsForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTrxAccountBalance_GetAccountsForUpdate_Call) Return(_a0 []*dao.AccountBalances, _a1 error) *MockTrxAccountBalance_GetAccountsForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrxAccountBalance_GetAccountsForUpdate_Call) RunAndReturn(run func(context.Context, []string) ([]*dao.AccountBalances, error)) *MockTrxAccountBalance_GetAccountsForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountBalance provides a mock function with given fields: ctx, params
func (_m *MockTrxAccountBalance) UpdateAccountBalance(ctx context.Context, params dao.UpdateAccountParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.UpdateAccountParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrxAccountBalance_UpdateAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountBalance'
type MockTrxAccountBalance_UpdateAccountBalance_Call struct {
	*mock.Call
}

// UpdateAccountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - params dao.UpdateAccountParams
func (_e *MockTrxAccountBalance_Expecter) UpdateAccountBalance(ctx interface{}, params interface{}) *MockTrxAccountBalance_UpdateAccountBalance_Call {
	return &MockTrxAccountBalance_UpdateAccountBalance_Call{Call: _e.mock.On("UpdateAccountBalance", ctx, params)}
}

func (_c *MockTrxAccountBalance_UpdateAccountBalance_Call) Run(run func(ctx context.Context, params dao.UpdateAccountParams)) *MockTrxAccountBalance_UpdateAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.UpdateAccountParams))
	})
	return _c
}

func (_c *MockTrxAccountBalance_UpdateAccountBalance_Call) Return(_a0 error) *MockTrxAccountBalance_UpdateAccountBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrxAccountBalance_UpdateAccountBalance_Call) RunAndReturn(run func(context.Context, dao.UpdateAccountParams) error) *MockTrxAccountBalance_UpdateAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrxAccountBalance creates a new instance of MockTrxAccountBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrxAccountBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrxAccountBalance {
	mock := &MockTrxAccountBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
