// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheck is an autogenerated mock type for the HealthCheck type
type MockHealthCheck struct {
	mock.Mock
}

type MockHealthCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheck) EXPECT() *MockHealthCheck_Expecter {
	return &MockHealthCheck_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *MockHealthCheck) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheck_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockHealthCheck_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthCheck_Expecter) Ping(ctx interface{}) *MockHealthCheck_Ping_Call {
	return &MockHealthCheck_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockHealthCheck_Ping_Call) Run(run func(ctx context.Context)) *MockHealthCheck_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthCheck_Ping_Call) Return(_a0 error) *MockHealthCheck_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheck_Ping_Call) RunAndReturn(run func(context.Context) error) *MockHealthCheck_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheck creates a new instance of MockHealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheck {
	mock := &MockHealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
