// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	dao "github.com/dhuki/go-ledger-system/internal/infra/database/dao"
	domain "github.com/dhuki/go-ledger-system/internal/infra/database/repository/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockDomainRepository is an autogenerated mock type for the DomainRepository type
type MockDomainRepository struct {
	mock.Mock
}

type MockDomainRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainRepository) EXPECT() *MockDomainRepository_Expecter {
	return &MockDomainRepository_Expecter{mock: &_m.Mock}
}

// GetAccountsForUpdate provides a mock function with given fields: ctx, accountNumbers
func (_m *MockDomainRepository) GetAccountsForUpdate(ctx context.Context, accountNumbers []string) ([]*dao.AccountBalances, error) {
	ret := _m.Called(ctx, accountNumbers)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsForUpdate")
	}

	var r0 []*dao.AccountBalances
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*dao.AccountBalances, error)); ok {
		return rf(ctx, accountNumbers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*dao.AccountBalances); ok {
		r0 = rf(ctx, accountNumbers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.AccountBalances)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, accountNumbers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDomainRepository_GetAccountsForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsForUpdate'
type MockDomainRepository_GetAccountsForUpdate_Call struct {
	*mock.Call
}

// GetAccountsForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumbers []string
func (_e *MockDomainRepository_Expecter) GetAccountsForUpdate(ctx interface{}, accountNumbers interface{}) *MockDomainRepository_GetAccountsForUpdate_Call {
	return &MockDomainRepository_GetAccountsForUpdate_Call{Call: _e.mock.On("GetAccountsForUpdate", ctx, accountNumbers)}
}

func (_c *MockDomainRepository_GetAccountsForUpdate_Call) Run(run func(ctx context.Context, accountNumbers []string)) *MockDomainRepository_GetAccountsForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockDomainRepository_GetAccountsForUpdate_Call) Return(_a0 []*dao.AccountBalances, _a1 error) *MockDomainRepository_GetAccountsForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDomainRepository_GetAccountsForUpdate_Call) RunAndReturn(run func(context.Context, []string) ([]*dao.AccountBalances, error)) *MockDomainRepository_GetAccountsForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransferByReferenceID provides a mock function with given fields: ctx, referenceID
func (_m *MockDomainRepository) GetTransferByReferenceID(ctx context.Context, referenceID string) (*dao.TransactionTransfers, error) {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransferByReferenceID")
	}

	var r0 *dao.TransactionTransfers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dao.TransactionTransfers, error)); ok {
		return rf(ctx, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dao.TransactionTransfers); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.TransactionTransfers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDomainRepository_GetTransferByReferenceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransferByReferenceID'
type MockDomainRepository_GetTransferByReferenceID_Call struct {
	*mock.Call
}

// GetTransferByReferenceID is a helper method to define mock.On call
//   - ctx context.Context
//   - referenceID string
func (_e *MockDomainRepository_Expecter) GetTransferByReferenceID(ctx interface{}, referenceID interface{}) *MockDomainRepository_GetTransferByReferenceID_Call {
	return &MockDomainRepository_GetTransferByReferenceID_Call{Call: _e.mock.On("GetTransferByReferenceID", ctx, referenceID)}
}

func (_c *MockDomainRepository_GetTransferByReferenceID_Call) Run(run func(ctx context.Context, referenceID string)) *MockDomainRepository_GetTransferByReferenceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDomainRepository_GetTransferByReferenceID_Call) Return(_a0 *dao.TransactionTransfers, _a1 error) *MockDomainRepository_GetTransferByReferenceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDomainRepository_GetTransferByReferenceID_Call) RunAndReturn(run func(context.Context, string) (*dao.TransactionTransfers, error)) *MockDomainRepository_GetTransferByReferenceID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLedgerEntriesBulk provides a mock function with given fields: ctx, entries
func (_m *MockDomainRepository) InsertLedgerEntriesBulk(ctx context.Context, entries []dao.LedgerEntries) error {
	ret := _m.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for InsertLedgerEntriesBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dao.LedgerEntries) error); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDomainRepository_InsertLedgerEntriesBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLedgerEntriesBulk'
type MockDomainRepository_InsertLedgerEntriesBulk_Call struct {
	*mock.Call
}

// InsertLedgerEntriesBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []dao.LedgerEntries
func (_e *MockDomainRepository_Expecter) InsertLedgerEntriesBulk(ctx interface{}, entries interface{}) *MockDomainRepository_InsertLedgerEntriesBulk_Call {
	return &MockDomainRepository_InsertLedgerEntriesBulk_Call{Call: _e.mock.On("InsertLedgerEntriesBulk", ctx, entries)}
}

func (_c *MockDomainRepository_InsertLedgerEntriesBulk_Call) Run(run func(ctx context.Context, entries []dao.LedgerEntries)) *MockDomainRepository_InsertLedgerEntriesBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dao.LedgerEntries))
	})
	return _c
}

func (_c *MockDomainRepository_InsertLedgerEntriesBulk_Call) Return(_a0 error) *MockDomainRepository_InsertLedgerEntriesBulk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDomainRepository_InsertLedgerEntriesBulk_Call) RunAndReturn(run func(context.Context, []dao.LedgerEntries) error) *MockDomainRepository_InsertLedgerEntriesBulk_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransfer provides a mock function with given fields: ctx, transfer
func (_m *MockDomainRepository) InsertTransfer(ctx context.Context, transfer dao.TransactionTransfers) (int64, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransfer")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.TransactionTransfers) (int64, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.TransactionTransfers) int64); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.TransactionTransfers) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDomainRepository_InsertTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransfer'
type MockDomainRepository_InsertTransfer_Call struct {
	*mock.Call
}

// InsertTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transfer dao.TransactionTransfers
func (_e *MockDomainRepository_Expecter) InsertTransfer(ctx interface{}, transfer interface{}) *MockDomainRepository_InsertTransfer_Call {
	return &MockDomainRepository_InsertTransfer_Call{Call: _e.mock.On("InsertTransfer", ctx, transfer)}
}

func (_c *MockDomainRepository_InsertTransfer_Call) Run(run func(ctx context.Context, transfer dao.TransactionTransfers)) *MockDomainRepository_InsertTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.TransactionTransfers))
	})
	return _c
}

func (_c *MockDomainRepository_InsertTransfer_Call) Return(_a0 int64, _a1 error) *MockDomainRepository_InsertTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDomainRepository_InsertTransfer_Call) RunAndReturn(run func(context.Context, dao.TransactionTransfers) (int64, error)) *MockDomainRepository_InsertTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDomainRepository) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDomainRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDomainRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDomainRepository_Expecter) Ping(ctx interface{}) *MockDomainRepository_Ping_Call {
	return &MockDomainRepository_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDomainRepository_Ping_Call) Run(run func(ctx context.Context)) *MockDomainRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDomainRepository_Ping_Call) Return(_a0 error) *MockDomainRepository_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDomainRepository_Ping_Call) RunAndReturn(run func(context.Context) error) *MockDomainRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockDomainRepository) Transaction(ctx context.Context, fn func(domain.DomainRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(domain.DomainRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDomainRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockDomainRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(domain.DomainRepository) error
func (_e *MockDomainRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockDomainRepository_Transaction_Call {
	return &MockDomainRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockDomainRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(domain.DomainRepository) error)) *MockDomainRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(domain.DomainRepository) error))
	})
	return _c
}

func (_c *MockDomainRepository_Transaction_Call) Return(_a0 error) *MockDomainRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDomainRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(domain.DomainRepository) error) error) *MockDomainRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountBalance provides a mock function with given fields: ctx, params
func (_m *MockDomainRepository) UpdateAccountBalance(ctx context.Context, params dao.UpdateAccountParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.UpdateAccountParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDomainRepository_UpdateAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountBalance'
type MockDomainRepository_UpdateAccountBalance_Call struct {
	*mock.Call
}

// UpdateAccountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - params dao.UpdateAccountParams
func (_e *MockDomainRepository_Expecter) UpdateAccountBalance(ctx interface{}, params interface{}) *MockDomainRepository_UpdateAccountBalance_Call {
	return &MockDomainRepository_UpdateAccountBalance_Call{Call: _e.mock.On("UpdateAccountBalance", ctx, params)}
}

func (_c *MockDomainRepository_UpdateAccountBalance_Call) Run(run func(ctx context.Context, params dao.UpdateAccountParams)) *MockDomainRepository_UpdateAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.UpdateAccountParams))
	})
	return _c
}

func (_c *MockDomainRepository_UpdateAccountBalance_Call) Return(_a0 error) *MockDomainRepository_UpdateAccountBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDomainRepository_UpdateAccountBalance_Call) RunAndReturn(run func(context.Context, dao.UpdateAccountParams) error) *MockDomainRepository_UpdateAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDomainRepository creates a new instance of MockDomainRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainRepository {
	mock := &MockDomainRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
