// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisClient is an autogenerated mock type for the RedisClient type
type MockRedisClient struct {
	mock.Mock
}

type MockRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisClient) EXPECT() *MockRedisClient_Expecter {
	return &MockRedisClient_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, key
func (_m *MockRedisClient) Del(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockRedisClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Del(ctx interface{}, key interface{}) *MockRedisClient_Del_Call {
	return &MockRedisClient_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockRedisClient_Del_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisClient_Del_Call) Return(_a0 error) *MockRedisClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Del_Call) RunAndReturn(run func(context.Context, string) error) *MockRedisClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockRedisClient) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRedisClient_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockRedisClient_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockRedisClient_Expecter) Name() *MockRedisClient_Name_Call {
	return &MockRedisClient_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockRedisClient_Name_Call) Run(run func()) *MockRedisClient_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisClient_Name_Call) Return(_a0 string) *MockRedisClient_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Name_Call) RunAndReturn(run func() string) *MockRedisClient_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockRedisClient) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRedisClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisClient_Expecter) Ping(ctx interface{}) *MockRedisClient_Ping_Call {
	return &MockRedisClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRedisClient_Ping_Call) Run(run func(ctx context.Context)) *MockRedisClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRedisClient_Ping_Call) Return(_a0 error) *MockRedisClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Ping_Call) RunAndReturn(run func(context.Context) error) *MockRedisClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockRedisClient) SetNX(ctx context.Context, key string, value interface{}, ttl time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) (bool, error)); ok {
		return rf(ctx, key, value, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) bool); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r1 = rf(ctx, key, value, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisClient_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockRedisClient_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *MockRedisClient_Expecter) SetNX(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockRedisClient_SetNX_Call {
	return &MockRedisClient_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, value, ttl)}
}

func (_c *MockRedisClient_SetNX_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *MockRedisClient_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRedisClient_SetNX_Call) Return(_a0 bool, _a1 error) *MockRedisClient_SetNX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisClient_SetNX_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) (bool, error)) *MockRedisClient_SetNX_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *MockRedisClient) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRedisClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisClient_Expecter) Stop(ctx interface{}) *MockRedisClient_Stop_Call {
	return &MockRedisClient_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockRedisClient_Stop_Call) Run(run func(ctx context.Context)) *MockRedisClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRedisClient_Stop_Call) Return(_a0 error) *MockRedisClient_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisClient_Stop_Call) RunAndReturn(run func(context.Context) error) *MockRedisClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisClient creates a new instance of MockRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisClient {
	mock := &MockRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
