// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dao "github.com/dhuki/go-ledger-system/internal/infra/database/dao"
	domain "github.com/dhuki/go-ledger-system/internal/infra/database/repository/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetTransferByReferenceID provides a mock function with given fields: ctx, referenceID
func (_m *MockRepository) GetTransferByReferenceID(ctx context.Context, referenceID string) (*dao.TransactionTransfers, error) {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransferByReferenceID")
	}

	var r0 *dao.TransactionTransfers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dao.TransactionTransfers, error)); ok {
		return rf(ctx, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dao.TransactionTransfers); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.TransactionTransfers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTransferByReferenceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransferByReferenceID'
type MockRepository_GetTransferByReferenceID_Call struct {
	*mock.Call
}

// GetTransferByReferenceID is a helper method to define mock.On call
//   - ctx context.Context
//   - referenceID string
func (_e *MockRepository_Expecter) GetTransferByReferenceID(ctx interface{}, referenceID interface{}) *MockRepository_GetTransferByReferenceID_Call {
	return &MockRepository_GetTransferByReferenceID_Call{Call: _e.mock.On("GetTransferByReferenceID", ctx, referenceID)}
}

func (_c *MockRepository_GetTransferByReferenceID_Call) Run(run func(ctx context.Context, referenceID string)) *MockRepository_GetTransferByReferenceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetTransferByReferenceID_Call) Return(_a0 *dao.TransactionTransfers, _a1 error) *MockRepository_GetTransferByReferenceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTransferByReferenceID_Call) RunAndReturn(run func(context.Context, string) (*dao.TransactionTransfers, error)) *MockRepository_GetTransferByReferenceID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransfer provides a mock function with given fields: ctx, transfer
func (_m *MockRepository) InsertTransfer(ctx context.Context, transfer dao.TransactionTransfers) (int64, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransfer")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.TransactionTransfers) (int64, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.TransactionTransfers) int64); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.TransactionTransfers) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransfer'
type MockRepository_InsertTransfer_Call struct {
	*mock.Call
}

// InsertTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transfer dao.TransactionTransfers
func (_e *MockRepository_Expecter) InsertTransfer(ctx interface{}, transfer interface{}) *MockRepository_InsertTransfer_Call {
	return &MockRepository_InsertTransfer_Call{Call: _e.mock.On("InsertTransfer", ctx, transfer)}
}

func (_c *MockRepository_InsertTransfer_Call) Run(run func(ctx context.Context, transfer dao.TransactionTransfers)) *MockRepository_InsertTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.TransactionTransfers))
	})
	return _c
}

func (_c *MockRepository_InsertTransfer_Call) Return(_a0 int64, _a1 error) *MockRepository_InsertTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertTransfer_Call) RunAndReturn(run func(context.Context, dao.TransactionTransfers) (int64, error)) *MockRepository_InsertTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockRepository) Transaction(ctx context.Context, fn func(domain.DomainRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(domain.DomainRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(domain.DomainRepository) error
func (_e *MockRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockRepository_Transaction_Call {
	return &MockRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(domain.DomainRepository) error)) *MockRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(domain.DomainRepository) error))
	})
	return _c
}

func (_c *MockRepository_Transaction_Call) Return(_a0 error) *MockRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(domain.DomainRepository) error) error) *MockRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
